export const PERMISSIONS = {
  BUY: 1 << 0,
  ADD: 1 << 1,
  DELETE: 1 << 2,
  EDIT: 1 << 3,
  VIEW_PRIVATE: 1 << 4,
  VIEW_PUBLIC: 1 << 5,
};

export const ROLES = {
  CUSTOMER: PERMISSIONS.BUY | PERMISSIONS.VIEW_PUBLIC,

  MANAGER:
    PERMISSIONS.BUY |
    PERMISSIONS.VIEW_PUBLIC |
    PERMISSIONS.VIEW_PRIVATE |
    PERMISSIONS.ADD |
    PERMISSIONS.EDIT,

  ADMIN: 63,
};
